### ISSUE TITLE
Provide a reference to TMDB website on the header

### ISSUE THREAD

**Issue by kartonki** [kartonki/ReactMovieDataBase#7]
**Is your feature request related to a problem? Please describe.**
When hovering over the header on the upper left corner, the logo for React Movie DB takes me to the home page, however, when doing the same on the upper right corner where the TMDB logo is, there is not action for me to click or nothing happens if I do.

**Describe the solution you'd like**
Ideally, I should be able to be redirected on a new browser tab/page to the TMDB website
![image](https://user-images.githubusercontent.com/433160/220746551-58a7092c-a7dd-4f2b-bbd9-d0c5ffa46017.png)

**Describe alternatives you've considered**
There are no alternatives to this, it must be done

**Additional context**
Credit is called out on the source code, but it should also be called out on the display

**Comment by traveler-pinkie** [comment]
Hi Kartonki
I'd like to give this a try. Can you assign it to me?

**Comment by kartonki** [comment]
> Hi Kartonki I'd like to give this a try. Can you assign it to me?

I'm sorry I missed your message, I was showing this repo to someone and we did this over a zoom call as an example, would have been great to get someone else to contribute, LMK what are your interests, this repo needs a change, it's been 4 years since the first time I added this, would be nice to take it to NextJS for example  :)
